name: user_repository
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
